# Generated by Django 4.1.4 on 2023-02-05 15:36

import HMRS_p.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic_user',
            name='email',
            field=models.EmailField(default=None, max_length=1000, null=True, validators=[HMRS_p.models.validate_email]),
        ),
    ]
