# Generated by Django 4.1.4 on 2023-03-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0002_alter_generic_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic_user',
            name='title',
            field=models.ForeignKey(choices=[('Επίκουρος Καθηγητής επί θητεία', 'Επίκουρος Καθηγητής επί θητεία'), ('Μόνιμος Επίκουρος Καθηγητής', 'Μόνιμος Επίκουρος Καθηγητής'), ('Αναπληρωτής Καθηγητής', 'Αναπληρωτής Καθηγητής'), ('Καθηγητής Α Βαθμίδας', 'Καθηγητής Α Βαθμίδας'), ('Α - Δ Εισαγωγική Δ', 'Α - Δ Εισαγωγική Δ'), ('Α - Ε Εισαγωγική Ε', 'Α - Ε Εισαγωγική Ε'), ('Καμία Τιμή', 'Καμία Τιμή')], null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.academictitle'),
        ),
    ]
