# Generated by Django 4.1.4 on 2023-03-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0003_alter_generic_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic_user',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.academictitle'),
        ),
    ]
