# Generated by Django 4.1.4 on 2023-03-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0006_alter_academictitle_acadtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic_user',
            name='work_Experience',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='myUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.generic_user'),
            preserve_default=False,
        ),
    ]
