# Generated by Django 4.1.4 on 2023-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0007_remove_generic_user_work_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='myUser',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='myUser',
            field=models.ManyToManyField(to='HMRS_p.generic_user'),
        ),
    ]
