# Generated by Django 4.1.4 on 2023-03-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0008_remove_workexperience_myuser_workexperience_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='myUser',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='myUser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.generic_user'),
            preserve_default=False,
        ),
    ]
