# Generated by Django 4.1.4 on 2023-03-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0009_remove_workexperience_myuser_workexperience_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='myUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.generic_user'),
        ),
    ]
