# Generated by Django 4.1.4 on 2023-03-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0011_remove_generic_user_emptype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_class',
            name='myUser',
        ),
        migrations.RemoveField(
            model_name='employeespecialization',
            name='myUser',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='myUser',
        ),
        migrations.RemoveField(
            model_name='salaryclass',
            name='myUser',
        ),
        migrations.AddField(
            model_name='generic_user',
            name='emp_Grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.grades'),
        ),
        migrations.AddField(
            model_name='generic_user',
            name='employeeClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.employee_class'),
        ),
        migrations.AddField(
            model_name='generic_user',
            name='employeeSpec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.employeespecialization'),
        ),
        migrations.AddField(
            model_name='generic_user',
            name='salaryCl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.salaryclass'),
        ),
    ]
