# Generated by Django 4.1.4 on 2023-03-30 12:03

import HMRS_p.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0013_rename_salarycl_generic_user_salary_cl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='depProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_change_info', models.CharField(default='Διαδικασία εξέλιξης σε επόμενη βαθμίδα βάσει νομοθεσίας', max_length=100)),
                ('scale_change', models.CharField(default='Κάθε 2 έτη', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DPprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='employeeSpecificType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltTitle', models.CharField(choices=[('Διδακτικό Ερευνητικό Προσωπικό', 'Διδακτικό Ερευνητικό Προσωπικό'), ('Εργαστηριακό Διδακτικό Προσωπικό', 'Εργαστηριακό Διδακτικό Προσωπικό'), ('Ειδικό Τεχνικό Εργαστηριακό Προσωπικό', 'Ειδικό Τεχνικό Εργαστηριακό Προσωπικό'), ('Διοικητικό Προσωπικό', 'Διοικητικό Προσωπικό'), ('Υπάλληλοι με απόσπαση', 'Υπάλληλοι με απόσπαση'), ('Εντεταλμένοι Διδάσκοντες', 'Εντεταλμένοι Διδάσκοντες')], default=None, max_length=1000)),
                ('shortTitle', models.CharField(choices=[('ΔΕΠ', 'ΔΕΠ'), ('ΕΔΙΠ', 'ΕΔΙΠ'), ('ΕΤΕΠ', 'ΕΤΕΠ'), ('ΔΠ', 'ΔΠ'), ('YA', 'YA'), ('ΕΔ', 'ΕΔ')], default=None, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='generic_user',
            old_name='empType',
            new_name='general_emp_Type',
        ),
        migrations.RemoveField(
            model_name='generic_user',
            name='emp_Grades',
        ),
        migrations.RemoveField(
            model_name='generic_user',
            name='employeeClass',
        ),
        migrations.RemoveField(
            model_name='generic_user',
            name='employeeSpec',
        ),
        migrations.RemoveField(
            model_name='generic_user',
            name='salary_Cl',
        ),
        migrations.RemoveField(
            model_name='generic_user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='working_relations',
            name='myUser',
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='shortTitle',
            field=models.CharField(choices=[('ΔΕΠ', 'ΔΕΠ'), ('ΔΠ', 'ΔΠ'), ('ΈΠ', 'EΠ')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='address',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='birthDate',
            field=models.DateField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='displayName',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='email',
            field=models.EmailField(default=None, max_length=20, null=True, validators=[HMRS_p.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='fathersName',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='idIssuer',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='issueDate',
            field=models.DateField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='mothersName',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generic_user',
            name='workAddress',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='gradeTypes',
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='UserAsg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.generic_user'),
        ),
        migrations.AddField(
            model_name='depprofile',
            name='UserAsg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.generic_user'),
        ),
        migrations.AddField(
            model_name='academictitle',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.depprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_class',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.dpprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeespecialization',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.dpprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generic_user',
            name='specific_emp_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.employeespecifictype'),
        ),
        migrations.AddField(
            model_name='working_relations',
            name='myProfile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HMRS_p.dpprofile'),
            preserve_default=False,
        ),
    ]
