# Generated by Django 4.1.4 on 2023-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0014_depprofile_dpprofile_employeespecifictype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academictitle',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='employee_class',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='employeespecialization',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='working_relations',
            name='myProfile',
        ),
        migrations.AddField(
            model_name='depprofile',
            name='acadTitle',
            field=models.CharField(choices=[('Επίκουρος Καθηγητής επί θητεία', 'Επίκουρος Καθηγητής επί θητεία'), ('Μόνιμος Επίκουρος Καθηγητής', 'Μόνιμος Επίκουρος Καθηγητής'), ('Αναπληρωτής Καθηγητής', 'Αναπληρωτής Καθηγητής'), ('Καθηγητής Α Βαθμίδας', 'Καθηγητής Α Βαθμίδας'), ('Α - Δ Εισαγωγική Δ', 'Α - Δ Εισαγωγική Δ'), ('Α - Ε Εισαγωγική Ε', 'Α - Ε Εισαγωγική Ε'), ('Καμία Τιμή', 'Καμία Τιμή')], default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='fullName',
            field=models.CharField(choices=[('Μόνιμος Υπάλληλος', 'Μόνιμος Υπάλληλος'), ('Ιδιωτικού δικαίου αορίστου χρόνου', 'Ιδιωτικού δικαίου αορίστου χρόνου'), ('Ιδιωτικού δικαίου ορισμένου χρόνου', 'Ιδιωτικού δικαίου ορισμένου χρόνου'), ('Σύμβαση εργασίας', 'Σύμβαση εργασίας')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='fullName2',
            field=models.CharField(choices=[('Πανεπιστημιακής Εκπαίδευση', 'Πανεπιστημιακής Εκπαίδευσης'), ('Τεχνολογικής Εκπαίδευσης', 'Τεχνολογικής Εκπαίδευσης'), ('Δευτεροβάθμιας Εκπαίδευσης', 'Δευτεροβάθμιας Εκπαίδευσης'), ('Υποχρεωτικής Εκπαίδευσης', 'Υποχρεωτικής Εκπαίδευσης')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='fullname3',
            field=models.CharField(choices=[('Διοικητικού - Οικονομικού', 'Διοικητικού - Οικονομικού'), ('Πληροφορικής', 'Πληροφορικής'), ('Διοικητικού - Λογιστικού', 'Διοικητικού - Λογιστικού'), ('Βιβλιοθηκονόμων', 'Βιβλιοθηκονόμων'), ('Μηχανικών', 'Μηχανικών'), ('Επιμελητών', 'Επιμελητών')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='shortName',
            field=models.CharField(choices=[('ΜΥ', 'ΜΥ'), ('ΙΔΑΧ', 'ΙΔΑΧ'), ('ΙΔΟΧ', 'ΙΔΟΧ'), ('ΣΕ', 'ΣΕ')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='shortName2',
            field=models.CharField(choices=[('ΠΕ', 'ΠΕ'), ('ΤΕ', 'ΤΕ'), ('ΔΕ', 'ΔΕ'), ('ΥΕ', 'ΥΕ')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='shortname3',
            field=models.CharField(choices=[('ΔΟ', 'ΔΟ'), ('ΠΛΗ', 'ΠΛΗ'), ('ΔΛ', 'ΔΛ'), ('ΒΙ', 'ΒΙ'), ('ΜΗΧ', 'ΜΗΧ'), ('ΕΠΙ', 'ΕΠΙ')], default=None, max_length=100),
        ),
    ]
