# Generated by Django 4.1.4 on 2023-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMRS_p', '0016_delete_academictitle_delete_employee_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpprofile',
            name='grade_change_info',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('Γ', 'Γ'), ('Δ', 'Δ'), ('Ε', 'Ε')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dpprofile',
            name='pay_scale_details',
            field=models.CharField(choices=[('MK:1', 'MK:1'), ('MK:2', 'MK:2'), ('MK:3', 'MK:3'), ('MK:4', 'MK:4'), ('MK:5', 'MK:5'), ('MK:6', 'MK:6'), ('MK:7', 'MK:7'), ('MK:8', 'MK:8'), ('MK:9', 'MK:9'), ('MK:10', 'MK:10'), ('MK:11', 'MK:11'), ('MK:12', 'MK:12'), ('MK:13', 'MK:13'), ('MK:14', 'MK:14'), ('MK:15', 'MK:15'), ('MK:16', 'MK:16'), ('MK:17', 'MK:17'), ('MK:18', 'MK:18'), ('MK:19', 'MK:19')], default=None, max_length=100),
        ),
    ]
